### ISSUE TITLE
Add /afk command

### ISSUE THREAD

**Issue by davidfowl** [JabbR/JabbR#237]
Away from keyboard.

**Comment by Zaidos** [comment]
Even better, be able to add an AFK message :)

Example: 
/afk 'I'll be back in 5!'

**Comment by davidfowl** [comment]
@Zaidos where should that message show up?

**Comment by Zaidos** [comment]
Tooltip/hover over on an AFK user's name.

**Comment by PureKrome** [comment]
I'm taking DIBS on this .. please :)

**Comment by sethwebster** [comment]
@PureKrome  all finished?

**Comment by steingrim** [comment]
The tooltip is a great idea and the afk message can still be displayed live, much like when someone enters or leaves the room.

Without perimeter: sgMarshall just went afk.
With perimeter: sgMarshall just went afk, “Will be back after walking the dog.”

Might I suggest also some visual cue? Either altering the logo in some manner -- perhaps indenting it slightly, or adding an ellipsis after the name (to indicate there’s more information), or simply adding AFK (like owner is added),   or some such?

**Comment by PureKrome** [comment]
Last night i started on this. I've got an icon i've added to the end of a name. I've got a message they can add. I've got to do the tooltip still and make sure all the rooms with this person in, are updated.

I've been basing my code off the gravatar.

I'm around 50% done right now :) not too long away...hopefully tonight i'll get another go on it. I just have to make sure i get my EF migrations right - i've not done that before.

**Comment by davidfowl** [comment]
@traemarshall if you do inline text you'll have to truncate it anyways and people don't always have 24" monitors around.

**Comment by PureKrome** [comment]
Ok :) looking good right now. This is an example of what I've got.

![Alt Text](http://i.imgur.com/KKmXZ.png)

That's a tooltip i've got when a mouse hovers over the icon. I've re-used the LIGHTBULB icon only because i don't know what Icon we all want. I went to noun project and thought of using a few icons, like
- [EMail icon](http://thenounproject.com/noun/mail/#icon-No429)
- [Price Tag icon](http://thenounproject.com/noun/price-tag/#icon-No422)
- [Crayon icon](http://thenounproject.com/noun/crayon/#icon-No392)
- [Pencil icon](http://thenounproject.com/noun/pencil/#icon-No347)

but they are all SVG's .. so i'm not sure what to do, how to resize. what size, blah blah blah. So any suggestions?

Secondly, I want to talk about what I've added so far.

**New Command** 
`/note {some text}`

Note? Wtf? this is an AFK? Right? Yep :) (keep reading and stick with me...) I've added a NOTE feature which 
- Adds an Icon after the `(Owner)` of a name (or a name, if no owner).
- Sends a message to the room where the user exists within.

So now we can add ANY note we want.

Next ...

**New Command**
`/afk {optional text}`

This just calls Note with the text "AFK {optional text}" Not sure if I should automatically put the optional text in parenthesis Or a dash. eg.
- AFK - pew pew pew pew
- AFK (pew pew pew pew)

If a user types `/note` with no text, it removes the icon.

Now - the only thing i'm not too sure about is if I should AUTO clear the note, if the note starts with AFK .. when i user types a command or just chats to the room.

Thoughts?

EDIT: Oh .. i'm not sure about Html encoding? and if the text is long ... do we word wrap? (i'll need to tetst :P)
EDIT 2: Or `/afk` with no text could do: `Afk (last seen at {time} {date})` ... Or maybe a `ChatUser` should have a new property called `DateTime? LastSeenOn` which is updated any time a command is entered ?

**Comment by davidfowl** [comment]
1. I think we never show the afk text or note text, they only appear in the tooltip. That way there's no need to worry about wrapping or truncating the message.
2. Auto clear makes sense for afk notes and we already have LastActivity on User no need to invent a new one.
3. We need 2 different icons, one for afk and one for notes (need to spend time looking at icons)
4. Just save the icon as png and make sure it scales to something that works like 16x16 or 16x20 or you'll have to worry about css changes.

**Comment by PureKrome** [comment]
> I think we never show the afk text or note text, they only appear in the tooltip. That way there's no need to worry about wrapping or truncating the message.

yeah .. i was never going to display the Note text .. only via a ToolTip (as shown in the sample image, above).

> Auto clear makes sense for afk notes

Rgr. i'll add that in.

> LastActivity on User no need to invent a new one

Ah - I didn't check .. just came to my head, when I was writing up that comment. Np at all :)

> We need 2 different icons, one for afk and one for notes (need to spend time looking at icons).

Np at all. that's a once second change to use a different image. 
I'll also add the ability to show 2 different images, one for AFK and one for NOTE. I'll also add the following, if no one has any objections :-

`class ChatUser 
...
public string IsAfk { get { return Note != null & Note.StartsWith("AFK "); } } // notice the SPACE after the text....`

Then i can easily use that property to check if a ChatPerson is afk, etc...

**Comment by davidfowl** [comment]
That property was probably supposed to be a bool. Make sure adding that doesn't affect EF's model change detection.

**Comment by PureKrome** [comment]
Oh yeah. i ment a bool. sorry. brain still asleep :)

**Comment by PureKrome** [comment]
Ok. i've now implimented the toggling of the Note images via Css.

I've also slightly refactored the to the following (which I don't really like...)

``` javascript
setUserTyping: function (user, roomName, isTyping) {
    var room = getRoomElements(roomName),
        $user = room.getUser(user.Name);

    // Hide the Afk note, if we're typing, including the current user.
    if (isTyping) {
        toggleNote(user, $user);
    }

    // Do not show typing indicator for current user
    if (user.Name === ui.getUserName()) {
        return;
    }

    if (isTyping) {
        $user.addClass('typing');
    }
    else {
        $user.removeClass('typing');
    }
},
```

Notice how I've had to remove the Afk note -before- the user name is checked? this is because i put the NOTE/AFk image on yourself .. so u know there's a note/afk there.

The above works.. i just feel that it might be slightly bruteforce cause EVERY time a person types, we basically check to remove. The reason this happens is because I don't record if a person WAS afk and now IS NOT. It's just a current snapshot -> are we or not, right now?

Lastly, I'm not sure were to tackle my last issue -> when a user joins a room, they do NOT have their note set in the UI.
So i'm guessing this might have something to do with jQuery templates? From looking through the code, I _think_ I've spotted something about this  .. like ..

``` javascript
<script id="new-user-template" type="text/x-jquery-tmpl">
        <li class="user" data-name="${name}">
            <img class="gravatar" src="http://www.gravatar.com/avatar/${hash}?s=16&d=mm" />
            <span class="name">${name}</span>
            <span class="owner">{{if owner}}(owner){{/if}}</span>
            <span class="note"></span>
        </li>
    </script>
```

and 

``` javascript
....
templates = {
    user: $('#new-user-template'),
    ....
```

but i'm not sure how to use em, where to use, etc. Any suggestions how I should handle people entering a room? Btw.. with that template html above .. i have no idea how to pass in any Note info .. cause my css just toggles the title attribute on that span AND adds/remove a class to that existing span. eg. `note, note afk, note message`.

**Comment by davidfowl** [comment]
- For the first issue, you can just check the class to see if afk is set right? Not sure what you mean by we don't have that state. 
- For your other issue, you need to pass the note information as part of the `UserViewModel` and render it as part of the template (look at the other properties, and look at `chat.addUser`).

**Comment by PureKrome** [comment]
> For the first issue, you can just check the class to see if afk is set right? Not sure what you mean by we don't have that state.

Yeah - my latest commit does have an IsAfk toggle (which is not persisted to the DB). What I ment about 'state' was with regards to how to smart-toggle off the icon. IMO, I was thinking that if the code says: if we WERE Afk but now we're back .. then remove the image. Unfortunately, we have no idea about the 'WERE' bit .. only the 'NOW' bit. So therefore, i'm just doing a brute force 'if !Afk, remove class' .. even though we might not have been afk.

> For your other issue, you need to pass the note information as part of the UserViewModel
> Kewl.. this I did in my first commit a while back....
> 
>  and render it as part of the template (look at the other properties, and look at chat.addUser)
> This was the bit I was not so sure about. But the suggestion to check out chat.AddUser I _think_ might be the key :) (I've not done any jQuery templating, so I'll need to figure that out quickly).

Besides that, we're nearly good to go :)

I'll show a screen shot of the browser once i've finished this last AddUser thingy.

The only error is a visual one - which I'll show when I post the screenie, soonish.

**Comment by PureKrome** [comment]
Woot - looking good now. 
- /Note {optional text} - adds a note icon AND tooltip text. (tested with HTML text and it's getting encoded).
- /Note  - this clears a note
- /Afk {optional text} - adds a note with the prepending text being "Afk "
- anytime a person types something, if they are Afk .. then the note is removed.

I still need two images as pngs.

Finally. here's the only busted piece of code => Some UI :( See how the template-image is on a new line.. i just need some help in fixing that css. 

``` css
.note
{
    display: block;
    width: 16px;
    height: 16px;
}

.note.afk
{
    background: url(Content/images/toast-on.png) no-repeat;
}

.note.message
{
    background: url(Content/images/toast-off.png) no-repeat;
}
```

![](http://i.imgur.com/KOKJi.png)

Besides that - ready to PR.

**Comment by Zaidos** [comment]
Currently in staging, the 'AFK' is displayed in the afk note. Is this intended?

**Comment by PureKrome** [comment]
Yep - that's the PREPENDED Text which i put in front of any AFK note.

so if you type `/afk Hi there!` then the tooltip will say `'Afk Hi There'`

I wasn't sure if i should auto add a minus between the prepended text and the optional text (if some exist) 
eg. `Afk - Hi There!`

or just drop the prepended text all together .. with the stopwatch icon now being the hint that the person is afk.

I think originally i was using only ONE icon ... which was why i wanted to differentiate between an AFK note and a PERM note .. but now that we have 2 .. it (the pre-pended text) might be obsolete.

I'll do whatever you peeps want :) I have no allegiance to the pre-pended text.

**Comment by sethwebster** [comment]
Personally, I think the AFK is good if pre-pended with dash, and if uppercased.  It's an acronym and I think it looks silly proper-cased.

**Comment by PureKrome** [comment]
I was also wondering if maybe a Date/Timestamp should be prepended before each note/afk?
- 1/1/2012 : 5:13pm { Note }
- 1/1/2012 : 5:13pm AFK
- 1/1/2012 : 5:13pm AFK - plane trip to Barbados .. BB in 8 hours.
- [1/1/2012 : 5:13pm] { Note }
- [1/1/2012 : 5:13pm] AFK - plane trip to Barbados .. BB in 8 hours.

**Comment by sethwebster** [comment]
use the $.timeago(datetime) function, for something like:

AFK - Headed to Barbados... 8 hours of fun! - about 5 hours ago

**Comment by davidfowl** [comment]
This is done.
