### ISSUE TITLE
Flag to auto-hide rich providers

### ISSUE THREAD

**Issue by andrewtobin** [JabbR/JabbR#380]
A request came through the room that wasn't un-silly, and that's to auto-hide the gifs/videos/other things based on a flag.

I know that those features are what add value, but some people are at work/or just don't want it.

Maybe a flag to just disable rich content is a good way to go?

**Comment by samandmoore** [comment]
it would be cool to have this be part of the user prefs like on a per room basis.

also, I think the nicest way to handle this would be to check if they want the richness hidden and if so just make them collapsed on insert so that they can still be toggled back and forth individually.

maybe we can also use this as an impetus to persist user preferences :P

**Comment by samandmoore** [comment]
- per user via a setting above the user list
- collapse content upon insert with icon and tooltip ("blah is content is collapsed because you have disabled content")
- icon-info-sign from bootstrap for icon

**Comment by samandmoore** [comment]
added a user setting that is stored per room in the jabbr cookie and is swappable via an icon on the top right.
