### ISSUE TITLE
Wikipedia Content provider

### ISSUE THREAD

**Issue by nschonni** [JabbR/JabbR#533]
Not sure if there is a JSON API or not

**Comment by schulz3000** [comment]
There is an API with different formats for mediawiki: 
http://www.mediawiki.org/wiki/API
http://www.mediawiki.org/wiki/API:Data_formats
It's also available for wikipedia.
Sample call to get informations about Albert Einstein in JSON format: http://en.wikipedia.org/w/api.php?format=json&action=query&titles=Albert%20Einstein&prop=revisions&rvprop=content

**Comment by InfinitiesLoop** [comment]
Content providers that are basically just capuring something from the pasted uri and mapping it to some static parameterized html can now be added dynamically because of #1078. 

Wikipedia doesn't have an embeddable uri/script, but there's a site "embed.ly" that provides one (any many others). Seems like it could be used. It of course also embeds social crap to propagate itself... but the beauty of the configurable content providers is that you can use it if you want, or if you don't, don't :) Example of a random article:

http://embed.ly/code?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FHoseyn_Arbabi
