### ISSUE TITLE
updating your flag doesn't update the image

### ISSUE THREAD

**Issue by xt0rted** [JabbR/JabbR#689]
If you already have your flag set and then change it the tooltip updates in real-time but the image stays as the old value. You need to refresh the site for the new image to show.

**Comment by cmaish** [comment]
The way that jQuery UI extends jQuery's removeClass seems to be the problem here.

jQuery's [removeClass](http://api.jquery.com/removeClass/) itself allows no argument, which removes all classes from an element; but jQuery UI's [removeClass](http://api.jqueryui.com/removeClass/) requires an argument.

Under the hood, at current jQuery uses (arguments.length === 0) to determine if no class was specified.  jQuery UI 1.9 just sends through undefined in the argument.  jQuery UI 1.10 passes through the original arguments through .apply (so the issue wouldn't occur on that version).

https://github.com/schulz3000/JabbR/commit/9449e8668f5877a702c619fe3379e10092a578ed is probably the easiest way around this issue.

**Comment by davidfowl** [comment]
This is fixed now.
