### ISSUE TITLE
Upload Images URL with spaces breaking linking

### ISSUE THREAD

**Issue by phillip-haydon** [JabbR/JabbR#778]
When uploading an image that contains a space, the code encode the spaces:

![Untitled](https://f.cloud.github.com/assets/895629/342461/a9ed9468-9da8-11e2-9f7a-b8d0d9cf222d.jpg)

**Comment by PureKrome** [comment]
![scott 3](https://f.cloud.github.com/assets/899878/342466/d68a3d28-9da8-11e2-9062-c8385ca266da.JPG)

source ^

**Comment by davidfowl** [comment]
Looks like a bug in the linkify plugin:

http://benalman.com/code/test/js-linkify/?x=https%3A%2F%2Fjabbrstaging.blob.core.windows.net%2Fjabbr-uploads%2FCapture+Space_5ac1.PNG

**Comment by cmaish** [comment]
Fixed and in prod.

**Comment by cmaish** [comment]
Well, a mitigation at least for uploads.  If you paste a URI that has a space in it ("https://jabbr.blob.core.windows.net/jabbr-uploads/scott 3_f786.JPG"), linkify won't recognise the full URI, but that's kind of expected behavior (it will recognise "https://jabbr.blob.core.windows.net/jabbr-uploads/scott%203_f786.JPG").
